apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: docs-template-for-dummies
  title: Documentation Template for dummies
  description: Create a new standalone documentation project for dummies
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: backstage/techdocs-core
  templater: cookiecutter
  type: documentation
  path: '.'

  schema:
    required:
      - component_id
      - description
      - dummyProperty
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9A-Z_.-]{1,63}$
        description: Unique name of the component
      dummyProperty:
        title: Dummy property
        type: string
        description: This is a property for dummies
      description:
        title: Description
        type: string
        description: Help others understand what these docs are about.
